CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "password" varchar,
  "email" varchar UNIQUE NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar NOT NULL,
  "account_type" varchar NOT NULL,
  "currency" varchar(3) NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "account_statements" (
  "account_id" int,
  "closing_date" date NOT NULL,
  "closing_balance" int NOT NULL,
  "total_credit" int NOT NULL,
  "total_debit" int NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "transaction_types" (
  "transaction_type_code" varchar(1) PRIMARY KEY,
  "description" varchar,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int,
  "transaction_date" date NOT NULL,
  "category_id" int,
  "amount" int NOT NULL,
  "description" varchar,
  "transaction_type_code" varchar(1),
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "parent_id" int,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

COMMENT ON COLUMN "account_statements"."closing_date" IS '12:00am 1st Day of next Month';
COMMENT ON COLUMN "account_statements"."closing_balance" IS 'At 12:00am 1st Day of next Month';
COMMENT ON COLUMN "account_statements"."total_credit" IS 'for closed month';
COMMENT ON COLUMN "account_statements"."total_debit" IS 'for closed month';

ALTER TABLE "accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "account_statements" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("transaction_type_code") REFERENCES "transaction_types" ("transaction_type_code");
ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id");
